/** Demo payloads for the hostless dev harness (`npm run dev` in a browser). */

import type {
  DashboardPayload,
  DetailPayload,
  ListPayload,
  RankingPayload,
  SearchPayload,
  SeasonalPayload,
  ViewPayload,
} from "../mcp/types";

const CDN = "https://cdn.myanimelist.net/images/anime";

const search: SearchPayload = {
  view: "search",
  kind: "anime",
  query: "frieren",
  count: 4,
  results: [
    {
      id: 52991,
      title: "Sousou no Frieren",
      picture: `${CDN}/1015/138006.jpg`,
      year: 2023,
      media_type: "tv",
      airing_status: "finished_airing",
      mean: 9.31,
      num_episodes: 28,
      genres: ["Adventure", "Drama", "Fantasy"],
      synopsis:
        "During their decade-long quest to defeat the Demon King, the members of the hero's party formed bonds they believed would last forever...",
    },
    {
      id: 5114,
      title: "Fullmetal Alchemist: Brotherhood",
      picture: `${CDN}/1208/94745.jpg`,
      year: 2009,
      media_type: "tv",
      airing_status: "finished_airing",
      mean: 9.1,
      num_episodes: 64,
      genres: ["Action", "Adventure", "Drama"],
      synopsis:
        "After a horrific alchemy experiment goes wrong in the Elric household, brothers Edward and Alphonse are left in a catastrophic new reality...",
    },
    {
      id: 9253,
      title: "Steins;Gate",
      picture: `${CDN}/1935/127974.jpg`,
      year: 2011,
      media_type: "tv",
      airing_status: "finished_airing",
      mean: 9.07,
      num_episodes: 24,
      genres: ["Drama", "Sci-Fi", "Suspense"],
      synopsis:
        "Eccentric scientist Rintarou Okabe has a never-ending thirst for scientific exploration...",
    },
    {
      id: 28977,
      title: "Gintama°",
      picture: `${CDN}/3/72078.jpg`,
      year: 2015,
      media_type: "tv",
      airing_status: "finished_airing",
      mean: 9.06,
      num_episodes: 51,
      genres: ["Action", "Comedy", "Sci-Fi"],
      synopsis: "Gintoki, Shinpachi, and Kagura return as the fun-loving but broke members of the Yorozuya team!",
    },
  ],
};

const detail: DetailPayload = {
  view: "detail",
  kind: "anime",
  id: 52991,
  title: "Sousou no Frieren",
  picture: `${CDN}/1015/138006.jpg`,
  picture_large: `${CDN}/1015/138006l.jpg`,
  alternative_titles: { en: "Frieren: Beyond Journey's End", ja: "葬送のフリーレン" },
  synopsis:
    "During their decade-long quest to defeat the Demon King, the members of the hero's party—Himmel himself, the priest Heiter, the dwarf warrior Eisen, and the elven mage Frieren—forge bonds through adventures and battles. However, the time that Frieren spends with her comrades is equivalent to merely a fraction of her life, which has lasted over a thousand years. When the party disbands after their victory, Frieren casually returns to her “usual” routine of collecting spells across the continent. Due to her different sense of time, she seemingly holds no strong feelings toward the experiences she went through. As the years pass, Frieren gradually realizes how her days in the hero's party truly impacted her.",
  mean: 9.31,
  rank: 1,
  popularity: 128,
  num_list_users: 1_180_432,
  num_scoring_users: 620_112,
  media_type: "tv",
  airing_status: "finished_airing",
  num_episodes: 28,
  year: 2023,
  start_date: "2023-09-29",
  end_date: "2024-03-22",
  source: "manga",
  average_episode_duration_sec: 1440,
  rating: "pg_13",
  genres: ["Adventure", "Drama", "Fantasy"],
  studios: ["Madhouse"],
  related_anime: [
    { id: 56805, title: "Sousou no Frieren: ●● no Mahou", relation_type: "side_story" },
  ],
  recommendations: [
    { id: 33352, title: "Violet Evergarden", num_recommendations: 21 },
    { id: 457, title: "Mushishi", num_recommendations: 18 },
    { id: 543, title: "Kino no Tabi", num_recommendations: 11 },
  ],
  statistics: {
    status: { watching: 214_000, completed: 690_000, on_hold: 41_000, dropped: 22_000, plan_to_watch: 213_000 },
    num_list_users: 1_180_432,
  },
  my_list_status: { status: "watching", score: 9, num_episodes_watched: 17 },
};

const list: ListPayload = {
  view: "list",
  kind: "anime",
  editable: true,
  total_returned: 5,
  offset: 0,
  has_more: true,
  entries: [
    {
      id: 52991,
      title: "Sousou no Frieren",
      picture: `${CDN}/1015/138006.jpg`,
      year: 2023,
      media_type: "tv",
      airing_status: "finished_airing",
      my_status: "watching",
      my_score: 9,
      episodes_watched: 17,
      total_episodes: 28,
      genres: ["Adventure", "Drama", "Fantasy"],
      mal_mean: 9.31,
      studios: ["Madhouse"],
      updated_at: "2026-06-30T21:04:00+00:00",
    },
    {
      id: 5114,
      title: "Fullmetal Alchemist: Brotherhood",
      picture: `${CDN}/1208/94745.jpg`,
      year: 2009,
      media_type: "tv",
      airing_status: "finished_airing",
      my_status: "completed",
      my_score: 10,
      episodes_watched: 64,
      total_episodes: 64,
      genres: ["Action", "Adventure", "Drama"],
      mal_mean: 9.1,
      studios: ["Bones"],
      updated_at: "2025-11-02T09:12:00+00:00",
    },
    {
      id: 9253,
      title: "Steins;Gate",
      picture: `${CDN}/1935/127974.jpg`,
      year: 2011,
      media_type: "tv",
      airing_status: "finished_airing",
      my_status: "completed",
      my_score: 9,
      episodes_watched: 24,
      total_episodes: 24,
      genres: ["Drama", "Sci-Fi", "Suspense"],
      mal_mean: 9.07,
      studios: ["White Fox"],
      updated_at: "2025-08-14T17:40:00+00:00",
    },
    {
      id: 48569,
      title: "86 Part 2",
      picture: `${CDN}/1111/117134.jpg`,
      year: 2021,
      media_type: "tv",
      airing_status: "finished_airing",
      my_status: "on_hold",
      my_score: 0,
      episodes_watched: 4,
      total_episodes: 12,
      genres: ["Drama", "Sci-Fi"],
      mal_mean: 8.7,
      studios: ["A-1 Pictures"],
      updated_at: "2025-05-20T08:00:00+00:00",
    },
    {
      id: 21,
      title: "One Piece",
      picture: `${CDN}/1244/138851.jpg`,
      year: 1999,
      media_type: "tv",
      airing_status: "currently_airing",
      my_status: "plan_to_watch",
      my_score: 0,
      episodes_watched: 0,
      total_episodes: 0,
      genres: ["Action", "Adventure", "Fantasy"],
      mal_mean: 8.73,
      studios: ["Toei Animation"],
      updated_at: "2025-01-05T13:37:00+00:00",
    },
  ],
};

const ranking: RankingPayload = {
  view: "ranking",
  kind: "anime",
  ranking_type: "airing",
  total_returned: 5,
  offset: 0,
  has_more: true,
  entries: [
    { rank: 1, previous_rank: 1, id: 52991, title: "Sousou no Frieren", picture: `${CDN}/1015/138006.jpg`, media_type: "tv", mean: 9.31, num_list_users: 1_180_432, genres: ["Adventure", "Drama"], year: 2023, num_episodes: 28, airing_status: "currently_airing" },
    { rank: 2, previous_rank: 4, id: 58514, title: "Kusuriya no Hitorigoto 2nd Season", picture: `${CDN}/1706/145012.jpg`, media_type: "tv", mean: 8.91, num_list_users: 410_221, genres: ["Drama", "Mystery"], year: 2025, num_episodes: 24, airing_status: "currently_airing" },
    { rank: 3, previous_rank: 2, id: 59027, title: "Chainsaw Man: Rekka-hen", picture: `${CDN}/1207/147290.jpg`, media_type: "movie", mean: 8.84, num_list_users: 380_115, genres: ["Action", "Fantasy"], year: 2025, num_episodes: 1, airing_status: "currently_airing" },
    { rank: 4, previous_rank: null, id: 60022, title: "One Punch Man Season 3", picture: `${CDN}/1069/146699.jpg`, media_type: "tv", mean: 8.7, num_list_users: 690_530, genres: ["Action", "Comedy"], year: 2025, num_episodes: 12, airing_status: "currently_airing" },
    { rank: 5, previous_rank: 3, id: 57334, title: "Vinland Saga Season 3", picture: `${CDN}/1170/124312.jpg`, media_type: "tv", mean: 8.65, num_list_users: 350_078, genres: ["Action", "Adventure", "Drama"], year: 2026, num_episodes: 24, airing_status: "currently_airing" },
  ],
};

const seasonal: SeasonalPayload = {
  view: "seasonal",
  kind: "anime",
  year: 2026,
  season: "summer",
  total_returned: ranking.entries.length,
  offset: 0,
  has_more: true,
  entries: ranking.entries.map(({ rank: _r, previous_rank: _p, ...rest }) => ({
    ...rest,
    rank: null,
    previous_rank: null,
  })),
};

const dashboard: DashboardPayload = {
  view: "dashboard",
  profile: {
    id: 1_234_567,
    name: "umut",
    picture: null,
    location: "Istanbul",
    joined_at: "2016-03-12T00:00:00+00:00",
    time_zone: "Europe/Istanbul",
    is_supporter: false,
    anime_statistics: {
      num_items_watching: 12,
      num_items_completed: 348,
      num_items_on_hold: 9,
      num_items_dropped: 21,
      num_items_plan_to_watch: 130,
      num_items: 520,
      num_days_watched: 94.6,
      num_days: 96.2,
      num_episodes: 5_612,
      num_times_rewatched: 14,
      mean_score: 7.84,
    },
  },
  stats: {
    total_entries: 520,
    status_distribution: { watching: 12, completed: 348, on_hold: 9, dropped: 21, plan_to_watch: 130 },
    scores: {
      scored_count: 355,
      mean: 7.84,
      median: 8,
      histogram_1_to_10: { "1": 2, "2": 3, "3": 5, "4": 12, "5": 24, "6": 48, "7": 82, "8": 98, "9": 58, "10": 23 },
    },
    episodes: { total_episodes_watched: 5_612, estimated_watch_hours: 2_266.1, estimated_watch_days: 94.4 },
    top_genres: [
      { name: "Action", count: 212, avg_my_score: 7.7 },
      { name: "Drama", count: 168, avg_my_score: 8.1 },
      { name: "Comedy", count: 141, avg_my_score: 7.5 },
      { name: "Fantasy", count: 128, avg_my_score: 7.9 },
      { name: "Sci-Fi", count: 94, avg_my_score: 8.0 },
      { name: "Romance", count: 76, avg_my_score: 7.2 },
      { name: "Mystery", count: 61, avg_my_score: 8.2 },
      { name: "Slice of Life", count: 54, avg_my_score: 7.1 },
    ],
    media_type_distribution: { tv: 402, movie: 68, ova: 28, special: 14, ona: 8 },
    release_decades: { "1990s": 22, "2000s": 84, "2010s": 261, "2020s": 153 },
    community_comparison: { avg_my_score_minus_mal_mean: -0.12, compared_entries: 341 },
    top_studios: [
      { name: "Madhouse", count: 34, avg_my_score: 8.2 },
      { name: "Bones", count: 29, avg_my_score: 8.0 },
      { name: "A-1 Pictures", count: 27, avg_my_score: 7.4 },
      { name: "Kyoto Animation", count: 22, avg_my_score: 8.4 },
      { name: "MAPPA", count: 21, avg_my_score: 7.9 },
    ],
  },
};

export const FIXTURES: Record<string, ViewPayload> = {
  search,
  detail,
  list,
  ranking,
  seasonal,
  dashboard,
};
